### PR TITLE
Replace "master" with "main" #BLM

### LINKED ISSUE #66: Consider renaming "master" to "main" #BLM
Some context: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

Edit: I wanted to say this is an **excellent** guide - succinct, clear, thorough - kudos! Would love to see it made more inclusive and have a lesser chance of evoking possibly painful memories.

### PR DESCRIPTION
**Pull request by anishkny**
Fixes #66

### CODE REVIEW

**Comment by anishkny** [comment]
Preview: https://visual-git-guide-anishkny.netlify.app

**Comment by MarkLodato** [comment]
Thanks for the contribution! Could you also rename `maint` to `stable`? Otherwise it's too confusing to have `maint` and `main` differ by a single letter.

**Comment by anishkny** [comment]
Sure, will try to get to it soon.

**Comment by anishkny** [comment]
@MarkLodato That's a good suggestion. Replaced `maint` with `stable`. Preview: https://visual-git-guide-anishkny.netlify.app

**Comment by MarkLodato** [comment]
Updated version is now live. Thanks again!

**Pull request merged**
